# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Vautopn < Formula
  desc "🚪 connect ipsec vpn via shell"
  homepage "https://github.com/mabdh/vautopn"
  url "https://github.com/mabdh/vautopn/archive/v0.0.8.tar.gz"
  sha256 "210eea159e84a9e595725ee3ce05255dfce9d03645bfe8ab2c0e3ebb579f768d"
  license ""

  depends_on "fzf" => :recommended
  depends_on "oath-toolkit" => :recommended

  def install
    bin.install "vautopn"
  end
end
